CREATE TABLE IF NOT EXISTS dataload (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    DBDATAONE TEXT NOT NULL,
    DBDATATWO TEXT NOT NULL,
    DBDATATHREE TEXT NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 1
);

